mex penalty.F90 sparsereg.F90 ...
    -L/usr/local/gfortran/lib/ -lgfortran ...
    -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.8.2 -lgfortranbegin ...
    -L/Applications/MATLAB_R2014a.app/bin/maci64 -lmx -lmex -lmat
mex lsqmaxlambda.F90 sparsereg.F90 ...
    -L/usr/local/gfortran/lib/ -lgfortran ...
    -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.8.2 -lgfortranbegin ...
    -L/Applications/MATLAB_R2014a.app/bin/maci64 -lmx -lmex -lmat
mex lsqsparse.F90 sparsereg.F90 ...
    -L/usr/local/gfortran/lib/ -lgfortran ...
    -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.8.2 -lgfortranbegin ...
    -L/Applications/MATLAB_R2014a.app/bin/maci64 -lmx -lmex -lmat
mex lsqthresholding.F90 sparsereg.F90 ...
    -L/usr/local/gfortran/lib/ -lgfortran ...
    -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.8.2 -lgfortranbegin ...
    -L/Applications/MATLAB_R2014a.app/bin/maci64 -lmx -lmex -lmat
mex glmsparse.F90 sparsereg.F90 ...
    -L/usr/local/gfortran/lib/ -lgfortran ...
    -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.8.2 -lgfortranbegin ...
    -L/Applications/MATLAB_R2014a.app/bin/maci64 -lmx -lmex -lmat
mex glmthresholding.F90 sparsereg.F90 ...
    -L/usr/local/gfortran/lib/ -lgfortran ...
    -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.8.2 -lgfortranbegin ...
    -L/Applications/MATLAB_R2014a.app/bin/maci64 -lmx -lmex -lmat
mex glmmaxlambda.F90 sparsereg.F90 ...
    -L/usr/local/gfortran/lib/ -lgfortran ...
    -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.8.2 -lgfortranbegin ...
    -L/Applications/MATLAB_R2014a.app/bin/maci64 -lmx -lmex -lmat
